// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZNvU2AjkhlWKZd4u041tWkFucQy48OLQ',
    appId: '1:669034337734:web:2543d5a79f32f656b50ec7',
    messagingSenderId: '669034337734',
    projectId: 'prottasha-app',
    authDomain: 'prottasha-app.firebaseapp.com',
    storageBucket: 'prottasha-app.firebasestorage.app',
    measurementId: 'G-WTZR113JGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmVrHhUMxRYs0Mvr0AtsEGHjyA2xizC14',
    appId: '1:669034337734:android:bf02a45b1cc11842b50ec7',
    messagingSenderId: '669034337734',
    projectId: 'prottasha-app',
    storageBucket: 'prottasha-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDStfSQiCIXcN1nGPtgWAXAWsEr92kMoKk',
    appId: '1:669034337734:ios:0198f17b6a22007bb50ec7',
    messagingSenderId: '669034337734',
    projectId: 'prottasha-app',
    storageBucket: 'prottasha-app.firebasestorage.app',
    iosBundleId: 'com.example.savingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDStfSQiCIXcN1nGPtgWAXAWsEr92kMoKk',
    appId: '1:669034337734:ios:0198f17b6a22007bb50ec7',
    messagingSenderId: '669034337734',
    projectId: 'prottasha-app',
    storageBucket: 'prottasha-app.firebasestorage.app',
    iosBundleId: 'com.example.savingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZNvU2AjkhlWKZd4u041tWkFucQy48OLQ',
    appId: '1:669034337734:web:fb1ac9ca8e7a7131b50ec7',
    messagingSenderId: '669034337734',
    projectId: 'prottasha-app',
    authDomain: 'prottasha-app.firebaseapp.com',
    storageBucket: 'prottasha-app.firebasestorage.app',
    measurementId: 'G-QWCL291GMY',
  );
}
