begin;

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id text,
  old_data jsonb,
  new_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_created_at_idx
  on public.audit_logs(created_at desc);
create index if not exists audit_logs_actor_id_idx
  on public.audit_logs(actor_id);

alter table public.audit_logs enable row level security;
drop policy if exists "admins_read_audit_logs" on public.audit_logs;
create policy "admins_read_audit_logs"
on public.audit_logs
for select
to authenticated
using (public.is_admin());

-- Clients cannot insert/update/delete audit rows directly.
revoke insert, update, delete on public.audit_logs from anon, authenticated;
grant select on public.audit_logs to authenticated;

create or replace function public.capture_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old jsonb;
  v_new jsonb;
  v_id text;
begin
  v_old := case when tg_op in ('UPDATE', 'DELETE')
    then to_jsonb(old) - array['fcm_token', 'document_url', 'receipt_url']
    else null end;
  v_new := case when tg_op in ('INSERT', 'UPDATE')
    then to_jsonb(new) - array['fcm_token', 'document_url', 'receipt_url']
    else null end;
  v_id := coalesce(v_new ->> 'id', v_old ->> 'id',
                   v_new ->> 'month_year', v_old ->> 'month_year');

  insert into public.audit_logs (
    actor_id, action, entity_type, entity_id, old_data, new_data
  ) values (
    auth.uid(), lower(tg_op), tg_table_name, v_id, v_old, v_new
  );
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'profiles', 'transactions', 'app_settings', 'monthly_requirements',
    'special_charges', 'notifications'
  ] loop
    execute format('drop trigger if exists audit_%I on public.%I',
                   table_name, table_name);
    execute format(
      'create trigger audit_%I after insert or update or delete on public.%I '
      'for each row execute function public.capture_audit_log()',
      table_name, table_name
    );
  end loop;
end;
$$;

create or replace function public.set_user_monthly_amount(
  target_user_id uuid,
  new_amount numeric
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admin can change monthly amount';
  end if;
  if new_amount < 0 then
    raise exception 'Monthly amount cannot be negative';
  end if;
  update public.profiles
  set monthly_amount = new_amount
  where id = target_user_id and role = 'user';
end;
$$;

create or replace function public.update_app_settings_admin(
  new_amount numeric,
  new_start_date date
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admin can update app settings';
  end if;
  if new_amount < 0 then
    raise exception 'Monthly amount cannot be negative';
  end if;
  update public.app_settings
  set monthly_amount = new_amount,
      start_date = new_start_date,
      updated_at = now()
  where id = 1;
end;
$$;

create or replace function public.set_month_requirement_admin(
  requirement_month date,
  requirement_amount numeric,
  requirement_title text,
  requirement_is_special boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Only admin can set monthly requirements';
  end if;
  if requirement_amount < 0 or trim(requirement_title) = '' then
    raise exception 'Invalid monthly requirement';
  end if;
  insert into public.monthly_requirements (
    month_year, amount, title, is_special
  ) values (
    date_trunc('month', requirement_month)::date,
    requirement_amount,
    trim(requirement_title),
    requirement_is_special
  )
  on conflict (month_year) do update
  set amount = excluded.amount,
      title = excluded.title,
      is_special = excluded.is_special;
end;
$$;

create or replace function public.send_admin_notification(
  notification_title text,
  notification_body text,
  notification_type text default 'general',
  target_user_id uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  notification_id uuid;
begin
  if not public.is_admin() then
    raise exception 'Only admin can send notifications';
  end if;
  if trim(notification_title) = '' or trim(notification_body) = '' then
    raise exception 'Notification title and body are required';
  end if;
  insert into public.notifications (user_id, title, body, type)
  values (
    target_user_id, trim(notification_title), trim(notification_body),
    notification_type
  )
  returning id into notification_id;
  return notification_id;
end;
$$;

revoke all on function public.set_user_monthly_amount(uuid, numeric)
  from public, anon;
revoke all on function public.update_app_settings_admin(numeric, date)
  from public, anon;
revoke all on function public.set_month_requirement_admin(date, numeric, text, boolean)
  from public, anon;
revoke all on function public.send_admin_notification(text, text, text, uuid)
  from public, anon;

grant execute on function public.set_user_monthly_amount(uuid, numeric)
  to authenticated;
grant execute on function public.update_app_settings_admin(numeric, date)
  to authenticated;
grant execute on function public.set_month_requirement_admin(date, numeric, text, boolean)
  to authenticated;
grant execute on function public.send_admin_notification(text, text, text, uuid)
  to authenticated;

commit;
